.TH zmq_init 3 "" "(c)2007-2009 FastMQ Inc." "0MQ User Manuals"
.SH NAME
zmq_init \- initialises 0MQ context
.SH SYNOPSIS
.B void *zmq_init (int app_threads, int io_threads, int flags);
.SH DESCRIPTION
.SH RETURN VALUE
.SH ERRORS
.SH EXAMPLE
.SH SEE ALSO
.SH AUTHOR
Martin Sustrik <sustrik at 250bpm dot com>
