.TH zmq_msg_copy 3 "" "(c)2007-2009 FastMQ Inc." "0MQ User Manuals"
.SH NAME
zmq_msg_copy \- copies content of a message to another message
.SH SYNOPSIS
.B int zmq_msg_copy (zmq_msg_t *dest, zmq_msg_t *src);
.SH DESCRIPTION
.SH RETURN VALUE
.SH ERRORS
.SH EXAMPLE
.SH SEE ALSO
.SH AUTHOR
Martin Sustrik <sustrik at 250bpm dot com>
