.TH zmq_poll 3 "" "(c)2007-2009 FastMQ Inc." "0MQ User Manuals"
.SH NAME
zmq_poll \- polls for events on a set of 0MQ and POSIX sockets
.SH SYNOPSIS
.B int zmq_poll (zmq_pollitem_t *items, int nitems);
.SH DESCRIPTION
.SH RETURN VALUE
.SH ERRORS
.SH EXAMPLE
.SH SEE ALSO
.SH AUTHOR
Martin Sustrik <sustrik at 250bpm dot com>
