.TH zmq_msg_size 3 "" "(c)2007-2009 FastMQ Inc." "0MQ User Manuals"
.SH NAME
zmq_msg_size \- retrieves size of the message content
.SH SYNOPSIS
.B size_t zmq_msg_size (zmq_msg_t *msg);
.SH DESCRIPTION
.SH RETURN VALUE
.SH ERRORS
.SH EXAMPLE
.SH SEE ALSO
.SH AUTHOR
Martin Sustrik <sustrik at 250bpm dot com>
