.TH zmq_strerror 3 "" "(c)2007-2009 FastMQ Inc." "0MQ User Manuals"
.SH NAME
zmq_strerror \- returns string describing the error number
.SH SYNOPSIS
.B const char *zmq_strerror (int errnum);
.SH DESCRIPTION
As 0MQ defines few additional (non-POSIX) error codes, standard
.IR strerror
isn't capable of translating those errors into human readable strings. Instead,
.IR zmq_strerror
should be used.
.SH RETURN VALUE
Returns string describing the error number.
.SH ERRORS
No errors are defined.
.SH EXAMPLE
.nf
void *ctx = zmq_init (1, 1, 0);
if (!ctx) {
    printf ("error occured during zmq_init: %s\\n", zmq_strerror (errno));
    abort ();
}
.fi
.SH SEE ALSO
.BR zmq (7)
.SH AUTHOR
Martin Sustrik <sustrik at 250bpm dot com>
