= zmq_msg_init_buffer(3)


== NAME
zmq_msg_init_buffer - initialise 0MQ message with buffer copy


== SYNOPSIS
*int zmq_msg_init_buffer (zmq_msg_t '*msg', const void '*buf', size_t 'size');*


== DESCRIPTION
The _zmq_msg_init_buffer()_ function shall allocate any resources required to
store a message 'size' bytes long and initialise the message object referenced
by 'msg' to represent a copy of the buffer referenced by the 'buf' and
'size' arguments.

The implementation shall choose whether to store message content on the stack
(small messages) or on the heap (large messages).

CAUTION: Never access 'zmq_msg_t' members directly, instead always use the
_zmq_msg_ family of functions.

CAUTION: The functions _zmq_msg_init()_, _zmq_msg_init_data()_,
_zmq_msg_init_buffer()_ and _zmq_msg_init_buffer()_ are mutually exclusive.
Never initialise the same 'zmq_msg_t' twice.


== RETURN VALUE
The _zmq_msg_init_buffer()_ function shall return zero if successful. Otherwise
it shall return `-1` and set 'errno' to one of the values defined below.


== ERRORS
*ENOMEM*::
Insufficient storage space is available.


== SEE ALSO
* xref:zmq_msg_init_data.adoc[zmq_msg_init_data]
* xref:zmq_msg_init_size.adoc[zmq_msg_init_size]
* xref:zmq_msg_init.adoc[zmq_msg_init]
* xref:zmq_msg_close.adoc[zmq_msg_close]
* xref:zmq_msg_data.adoc[zmq_msg_data]
* xref:zmq_msg_size.adoc[zmq_msg_size]
* xref:zmq.adoc[zmq]


== AUTHORS
This page was written by the 0MQ community. To make a change please
read the 0MQ Contribution Policy at <https://zeromq.org/how-to-contribute/>.
