= zmq_vmci(7)


== NAME
zmq_vsock - 0MQ transport over Linux vsock(7) and Microsoft Hyper-V sockets


== SYNOPSIS
TBD


== ADDRESSING
A 0MQ endpoint is a string consisting of a 'transport'`://` followed by an
'address'. The 'transport' specifies the underlying protocol to use. The
'address' specifies the transport-specific address to connect to.

For the vsock(7) and Mictosoft Hyper-V transport, the transport is `vsock`,
and the meaning of the 'address' part is defined below.


Binding a socket
~~~~~~~~~~~~~~~~
TBD

Unbinding wild-card address from a socket
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TBD

Connecting a socket
~~~~~~~~~~~~~~~~~~~
TBD

== EXAMPLES
.Assigning a local address to a socket
----
//  VMCI port 5555 on all available interfaces
rc = zmq_bind(socket, "vsock://*:5555");
assert (rc == 0);
----

.Connecting a socket
----
//  Connecting using a VM ID
sprintf(endpoint, "vsock://%d:5555", vmid);
rc = zmq_connect(socket, endpoint);
assert (rc == 0);
----


== SEE ALSO
* xref:zmq_bind.adoc[zmq_bind]
* xref:zmq_connect.adoc[zmq_connect]
* xref:zmq_inproc.adoc[zmq_inproc]
* xref:zmq_tcp.adoc[zmq_tcp]
* xref:zmq_pgm.adoc[zmq_pgm]
* xref:zmq_vmci.adoc[zmq_vmci]
* xref:zmq_vsock.adoc[zmq_vsock]
* xref:zmq_getsockopt.adoc[zmq_getsockopt]
* xref:zmq.adoc[zmq]


== AUTHORS
This page was written by the 0MQ community. To make a change please
read the 0MQ Contribution Policy at <https://zeromq.org/how-to-contribute/>.
