# CMake generated Testfile for 
# Source directory: /Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests
# Build directory: /Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_ypipe "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Debug/unittest_ypipe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_ypipe "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Release/unittest_ypipe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_ypipe "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/MinSizeRel/unittest_ypipe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_ypipe "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/RelWithDebInfo/unittest_ypipe")
  set_tests_properties(unittest_ypipe PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_ypipe NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_poller "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Debug/unittest_poller")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_poller "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Release/unittest_poller")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_poller "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/MinSizeRel/unittest_poller")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_poller "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/RelWithDebInfo/unittest_poller")
  set_tests_properties(unittest_poller PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_poller NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_mtrie "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Debug/unittest_mtrie")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_mtrie "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Release/unittest_mtrie")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_mtrie "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/MinSizeRel/unittest_mtrie")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_mtrie "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/RelWithDebInfo/unittest_mtrie")
  set_tests_properties(unittest_mtrie PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_mtrie NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_ip_resolver "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Debug/unittest_ip_resolver")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_ip_resolver "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Release/unittest_ip_resolver")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_ip_resolver "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/MinSizeRel/unittest_ip_resolver")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_ip_resolver "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/RelWithDebInfo/unittest_ip_resolver")
  set_tests_properties(unittest_ip_resolver PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_ip_resolver NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_udp_address "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Debug/unittest_udp_address")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_udp_address "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Release/unittest_udp_address")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_udp_address "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/MinSizeRel/unittest_udp_address")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_udp_address "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/RelWithDebInfo/unittest_udp_address")
  set_tests_properties(unittest_udp_address PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_udp_address NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(unittest_radix_tree "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Debug/unittest_radix_tree")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(unittest_radix_tree "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/Release/unittest_radix_tree")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(unittest_radix_tree "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/MinSizeRel/unittest_radix_tree")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(unittest_radix_tree "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/bin/RelWithDebInfo/unittest_radix_tree")
  set_tests_properties(unittest_radix_tree PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;52;add_test;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/unittests/CMakeLists.txt;0;")
else()
  add_test(unittest_radix_tree NOT_AVAILABLE)
endif()
