# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget libzmq libzmq-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target libzmq
add_library(libzmq SHARED IMPORTED)

set_target_properties(libzmq PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/include;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode"
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libsodium.dylib"
)

# Create imported target libzmq-static
add_library(libzmq-static STATIC IMPORTED)

set_target_properties(libzmq-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ZMQ_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/include;/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode"
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libsodium.dylib"
)

# Import target "libzmq" for configuration "Debug"
set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libzmq PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/Debug/libzmq.5.2.3.dylib"
  IMPORTED_SONAME_DEBUG "@rpath/libzmq.5.dylib"
  )

# Import target "libzmq-static" for configuration "Debug"
set_property(TARGET libzmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libzmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LOCATION_DEBUG "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/Debug/libzmq.a"
  )

# Import target "libzmq" for configuration "Release"
set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libzmq PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/Release/libzmq.5.2.3.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/libzmq.5.dylib"
  )

# Import target "libzmq-static" for configuration "Release"
set_property(TARGET libzmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libzmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/Release/libzmq.a"
  )

# Import target "libzmq" for configuration "MinSizeRel"
set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(libzmq PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/MinSizeRel/libzmq.5.2.3.dylib"
  IMPORTED_SONAME_MINSIZEREL "@rpath/libzmq.5.dylib"
  )

# Import target "libzmq-static" for configuration "MinSizeRel"
set_property(TARGET libzmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(libzmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/MinSizeRel/libzmq.a"
  )

# Import target "libzmq" for configuration "RelWithDebInfo"
set_property(TARGET libzmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(libzmq PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/RelWithDebInfo/libzmq.5.2.3.dylib"
  IMPORTED_SONAME_RELWITHDEBINFO "@rpath/libzmq.5.dylib"
  )

# Import target "libzmq-static" for configuration "RelWithDebInfo"
set_property(TARGET libzmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(libzmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/lib/RelWithDebInfo/libzmq.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
