# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/steph/Documents/CloudStation/ingescape/code/libzmq/tests/CMakeLists.txt))

/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.15.4/bin/cmake -H/Users/steph/Documents/CloudStation/ingescape/code/libzmq -B/Users/steph/Documents/CloudStation/ingescape/code/libzmq/builds/xcode
